# FOR LOCAL DEVELOPMENT PURPOSES #
version: "3.7"
services:
  kafka:
    image: lensesio/fast-data-dev
    container_name: streams-kafka
    hostname: streams-kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - "ADVERTISED_HOST=streams-kafka"
      - "ADVERTISED_PORT=9092"

  word-count:
    depends_on:
      - kafka
    container_name: word-count
    image: smuehr/word-count:latest
    ports:
      - "8080:8080"
    environment:
      TZ: "Europe/Berlin"

  favourite-colour:
    depends_on:
      - kafka
    container_name: favourite-colour
    image: smuehr/favourite-colour:latest
    ports:
      - "8081:8080"
    environment:
      TZ: "Europe/Berlin"

  bank-balance-producer:
    depends_on:
      - kafka
    container_name: bank-balance-producer
    image: smuehr/bank-balance-producer:latest
    ports:
      - "8082:8080"
    environment:
      TZ: "Europe/Berlin"

  bank-balance:
    depends_on:
      - kafka
    container_name: bank-balance
    image: smuehr/bank-balance:latest
    ports:
      - "8083:8080"
    environment:
      TZ: "Europe/Berlin"

  user-data-producer:
    depends_on:
      - kafka
    container_name: user-data-producer
    image: smuehr/user-data-producer:latest
    ports:
      - "8084:8080"
    environment:
      TZ: "Europe/Berlin"

  user-event-enricher:
    depends_on:
      - kafka
    container_name: user-event-enricher
    image: smuehr/user-event-enricher:latest
    ports:
      - "8085:8080"
    environment:
      TZ: "Europe/Berlin"
